AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bedrock Chatbot - Lambda and API Gateway'

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeAgent
                  - bedrock:InvokeModel
                Resource: '*'

  # Lambda Function
  BedrockAgentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: bedrockAgentHandler
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import { BedrockAgentRuntimeClient, InvokeAgentCommand } from "@aws-sdk/client-bedrock-agent-runtime";

          const AGENT_ID = 'ZOZI3PH32D';
          const AGENT_ALIAS_ID = 'LC2IPXGFJV';
          const REGION = 'us-west-2';

          const client = new BedrockAgentRuntimeClient({ region: REGION });

          export const handler = async (event) => {
            try {
              const body = JSON.parse(event.body);
              const { message, sessionId } = body;

              if (!message) {
                return {
                  statusCode: 400,
                  headers: {
                    "Access-Control-Allow-Origin": "*",
                    "Access-Control-Allow-Headers": "*"
                  },
                  body: JSON.stringify({ error: "Missing required parameter: message" })
                };
              }

              const command = new InvokeAgentCommand({
                agentId: AGENT_ID,
                agentAliasId: AGENT_ALIAS_ID,
                sessionId: sessionId || `session-${Date.now()}`,
                inputText: message
              });

              const response = await client.send(command);
              
              let agentResponse = "";
              for await (const event of response.completion) {
                if (event.chunk) {
                  const chunk = event.chunk;
                  if (chunk.bytes) {
                    agentResponse += new TextDecoder().decode(chunk.bytes);
                  }
                }
              }

              return {
                statusCode: 200,
                headers: {
                  "Access-Control-Allow-Origin": "*",
                  "Access-Control-Allow-Headers": "*"
                },
                body: JSON.stringify({ 
                  response: agentResponse || "No response from agent"
                })
              };
            } catch (error) {
              console.error("Error invoking Bedrock agent:", error);
              return {
                statusCode: 500,
                headers: {
                  "Access-Control-Allow-Origin": "*",
                  "Access-Control-Allow-Headers": "*"
                },
                body: JSON.stringify({ error: error.message })
              };
            }
          };

  # API Gateway
  ChatbotApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: BedrockChatbotAPI
      Description: API for Bedrock Chatbot

  # API Gateway Resource
  ChatResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ChatbotApi
      ParentId: !GetAtt ChatbotApi.RootResourceId
      PathPart: chat

  # API Gateway Method
  ChatPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ChatbotApi
      ResourceId: !Ref ChatResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BedrockAgentFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # CORS OPTIONS Method
  ChatOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ChatbotApi
      ResourceId: !Ref ChatResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ChatPostMethod
      - ChatOptionsMethod
    Properties:
      RestApiId: !Ref ChatbotApi
      StageName: prod

  # Lambda Permission for API Gateway
  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BedrockAgentFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ChatbotApi}/*/*

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ChatbotApi}.execute-api.${AWS::Region}.amazonaws.com/prod
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt BedrockAgentFunction.Arn
